<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MicroWrath.Core" Version="0.9.2-*" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="$(WrathPath)\Wrath_Data\Managed\UnityModManager\0Harmony.dll" Private="False" />
    <Reference Include="$(WrathPath)\Wrath_Data\Managed\Assembly-CSharp-firstpass.dll" Private="False" />
    <Reference Include="$(WrathPath)\Wrath_Data\Managed\Unity*.dll" Private="false" />
    <Reference Include="$(WrathPath)\Wrath_Data\Managed\Core*.dll" Private="false" />
    <Reference Include="$(WrathPath)\Wrath_Data\Managed\Owlcat*.dll" Publicize="true" Private="false" />
    <Reference Include="$(WrathPath)\Wrath_Data\Managed\Assembly-CSharp.dll*" Publicize="true" Private="false" />
    <Reference Include="$(WrathPath)\Wrath_Data\Managed\UnityModManager\UnityModManager.dll*" Publicize="true" Private="false" />
    <Reference Include="$(WrathPath)\Wrath_Data\Managed\Newtonsoft.Json.dll*" Private="false" />
    <Reference Include="$(WrathPath)\Wrath_Data\Managed\UnityModManager\0Harmony.dll*" Private="false" />
    <Reference Include="$(WrathPath)\Wrath_Data\Managed\UniRx.dll*" Private="False" />
  </ItemGroup>

</Project>
